### PR TITLE
fix: exposes ref in Checkbox, Radio and AutoComplete components

### PR DESCRIPTION
**Pull request by gepd**
## Checklist

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information

- Exposes the `ref` property of `radio`, `checkbox` and `auto-complete`
- Added tests and docs

### CODE REVIEW

**Comment by gepd** [comment]
I don't know why the development failed @unix can you help me?

**Comment by unix** [comment]
The Build failure is related to the scope check of the next build command, wait a moment while I create a PR to fix this scope check.

**Comment by gepd** [comment]
Thanks @unix I forgot to ask, what you think about this PR?

**Comment by gepd** [comment]
@unix can you  review this PR as well?

**Comment by unix** [comment]
This PR needs to be put on hold for a while, and I actually want all work on export types to start after #531 is completed.  (I plan to make a relatively large change to the export type in 531)
PS: this feature is planned to be included in 2.2.0.

**Comment by unix** [comment]
The implementation of this component is on hold and is not expected to be merged in the near future.

**Pull request closed without merging**
